/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.SinhVien;
import model.Tinh;

/**
 *
 * @author Tran Quoc Thai - CE181618
 */
public class QuanLiSV extends javax.swing.JFrame {

    public ArrayList<SinhVien> dsSinhVien = new ArrayList<>();

    public ArrayList<SinhVien> getDsSinhVien() {
        return dsSinhVien;
    }

    public void setDsSinhVien(ArrayList<SinhVien> dsSinhVien) {
        this.dsSinhVien = dsSinhVien;
    }

    public Tinh tinh;
    SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    String strHinhAnh = null;
    int index = -1;
    String strhinhAnh = "";

    /**
     * Creates new form QuanLiSV
     */
    public QuanLiSV() {
        initComponents();
        setLocationRelativeTo(null);
        jComboBox1quequan.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1_tim2 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1_maSV = new javax.swing.JLabel();
        jLabel2_timMSV = new javax.swing.JLabel();
        jLabel3_ngaySinh = new javax.swing.JLabel();
        jLabel4_hvaTen = new javax.swing.JLabel();
        jLabel5_gioiTInh = new javax.swing.JLabel();
        jLabel6_diemTb = new javax.swing.JLabel();
        jLabel7_queQuan = new javax.swing.JLabel();
        jTextField1_tim = new javax.swing.JTextField();
        jTextField2_msv = new javax.swing.JTextField();
        jTextField3thoten = new javax.swing.JTextField();
        jTextField5ngaySinh = new javax.swing.JTextField();
        jButton1_tim = new javax.swing.JButton();
        jTextField9DTB = new javax.swing.JTextField();
        jComboBox1quequan = new javax.swing.JComboBox<>();
        jRadioButton1Nam = new javax.swing.JRadioButton();
        jRadioButton2Nu = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1_hinhAnh = new javax.swing.JLabel();
        jButton1_first = new javax.swing.JButton();
        jButton1_down = new javax.swing.JButton();
        jButton1_up = new javax.swing.JButton();
        jButton1_last = new javax.swing.JButton();
        jButton1_xoa = new javax.swing.JButton();
        jButton1_them1 = new javax.swing.JButton();
        jButton1_sua = new javax.swing.JButton();
        jButton1_luu = new javax.swing.JButton();
        jButton1_huy1 = new javax.swing.JButton();
        jButton1_openFile = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jButton1_tim2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1_tim2.setText("TÌm");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1_maSV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1_maSV.setText("Mã Sinh Viên :");

        jLabel2_timMSV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2_timMSV.setText("Mã Sinh Viên :");

        jLabel3_ngaySinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3_ngaySinh.setText("Ngày Sinh");

        jLabel4_hvaTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4_hvaTen.setText("Họ Và Tên");

        jLabel5_gioiTInh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5_gioiTInh.setText("Giới Tính");

        jLabel6_diemTb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6_diemTb.setText("Điểm TB:");

        jLabel7_queQuan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7_queQuan.setText("Quê Quán");

        jTextField1_tim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField2_msv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField3thoten.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField5ngaySinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1_tim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1_tim.setText("TÌm");
        jButton1_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_timActionPerformed(evt);
            }
        });

        jTextField9DTB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jComboBox1quequan.setEditable(true);
        jComboBox1quequan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ArrayList<Tinh> list = Tinh.getdsTinh();
        jComboBox1quequan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1quequanActionPerformed(evt);
            }
        });
        jComboBox1quequan.addItem("");
        for (Tinh t : list) {
            jComboBox1quequan.addItem(t.getTenTinh());
        }

        buttonGroup1.add(jRadioButton1Nam);
        jRadioButton1Nam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton1Nam.setText("Nam");

        buttonGroup1.add(jRadioButton2Nu);
        jRadioButton2Nu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton2Nu.setText("Nữ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SV", "Họ Và Tên", "Quê Quán", "Ngày Sinh", "Giới Tính", "Điểm TB", "Xếp Loại"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1_hinhAnh.setText("Hình ảnh");
        jLabel1_hinhAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_hinhAnhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1_hinhAnh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1_hinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
        );

        jButton1_first.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1_first.setText("|<");
        jButton1_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_firstActionPerformed(evt);
            }
        });

        jButton1_down.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1_down.setText("<<");
        jButton1_down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_downActionPerformed(evt);
            }
        });

        jButton1_up.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1_up.setText(">>");
        jButton1_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_upActionPerformed(evt);
            }
        });

        jButton1_last.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1_last.setText(">|");
        jButton1_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_lastActionPerformed(evt);
            }
        });

        jButton1_xoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1_xoa.setText("Xóa");
        jButton1_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_xoaActionPerformed(evt);
            }
        });

        jButton1_them1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1_them1.setText("Thêm");
        jButton1_them1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_them1ActionPerformed(evt);
            }
        });

        jButton1_sua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1_sua.setText("Sửa");
        jButton1_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_suaActionPerformed(evt);
            }
        });

        jButton1_luu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1_luu.setText("Lưu");
        jButton1_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_luuActionPerformed(evt);
            }
        });

        jButton1_huy1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1_huy1.setText("Hủy");
        jButton1_huy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_huy1ActionPerformed(evt);
            }
        });

        jButton1_openFile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1_openFile.setText("Mở File");
        jButton1_openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_openFileActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jLabel2_timMSV, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jButton1_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel3_ngaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7_queQuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4_hvaTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1_maSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jTextField2_msv, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGap(14, 14, 14)
                                                    .addComponent(jTextField3thoten, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jTextField5ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jComboBox1quequan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel6_diemTb, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                            .addComponent(jLabel5_gioiTInh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addComponent(jRadioButton1Nam)
                                                .addGap(59, 59, 59)
                                                .addComponent(jRadioButton2Nu))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField9DTB)))))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton1_them1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton1_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton1_first)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton1_down)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1_up)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton1_last))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton1_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)
                                            .addComponent(jButton1_huy1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton1_openFile, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 74, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1_tim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1_tim)
                            .addComponent(jLabel2_timMSV, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1_maSV, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2_msv))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4_hvaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3thoten))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7_queQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1quequan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5ngaySinh)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5_gioiTInh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1Nam)
                    .addComponent(jRadioButton2Nu)
                    .addComponent(jButton1_xoa)
                    .addComponent(jButton1_them1)
                    .addComponent(jButton1_sua))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6_diemTb, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField9DTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1_luu)
                        .addComponent(jButton1_huy1)
                        .addComponent(jButton1_openFile)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1_down, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1_first, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1_up, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1_last, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public SinhVien getAllSinhVien() throws ParseException {
        SinhVien sv = new SinhVien();
        sv.setMaSV(jTextField2_msv.getText());
        sv.setHoVaTen(jTextField3thoten.getText());
        int quequan = jComboBox1quequan.getSelectedIndex() - 1;
        Tinh tinh = Tinh.getbyID(quequan);
        sv.setQueQuan(tinh);
        sv.setNgaySinh(format.parse(jTextField5ngaySinh.getText()));
        boolean gt = true;
        gt = jRadioButton1Nam.isSelected();
        sv.setGioiTinh(gt);
        sv.setDiemTB(Float.parseFloat(jTextField9DTB.getText()));
        if(strhinhAnh == (null)){
           sv.setHinhAnh("NO AVATAR");
       }else {
           sv.setHinhAnh(strhinhAnh);
       }
        dsSinhVien.add(sv);
        return sv;
    }

    public void fillDataTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (SinhVien sv : dsSinhVien) {
            model.addRow(new Object[]{
                sv.getMaSV(), sv.getHoVaTen(), sv.getQueQuan().getTenTinh(), format.format(sv.getNgaySinh()), sv.isGioiTinh() ? "Nam" : "Nữ", sv.getDiemTB() + "", sv.xeploai()
            });
        }
    }

    public void reset() {
        jTextField2_msv.setText("");
        jTextField3thoten.setText("");
        jComboBox1quequan.setSelectedIndex(-1);
        jTextField5ngaySinh.setText("");
        buttonGroup1.clearSelection();
        jTextField9DTB.setText("");

    }

    public void fillDateSinhVien(int index) {
        SinhVien sv = dsSinhVien.get(index);
        jTextField2_msv.setText(dsSinhVien.get(index).getMaSV());
        jTextField3thoten.setText(dsSinhVien.get(index).getHoVaTen());
        jComboBox1quequan.setSelectedItem(dsSinhVien.get(index).getQueQuan().getTenTinh());
        jTextField5ngaySinh.setText(format.format(dsSinhVien.get(index).getNgaySinh()));

        if (sv.isGioiTinh()) {
            jRadioButton1Nam.setSelected(true);

        } else {
            jRadioButton2Nu.setSelected(true);

        }
        jTextField9DTB.setText(String.valueOf(dsSinhVien.get(index).getDiemTB()));
        if(sv.getHinhAnh().equalsIgnoreCase("NO AVATAR")){
            jLabel1_hinhAnh.setText("No AVATAR");
             jLabel1_hinhAnh.setIcon(null);
        }else {
             jLabel1_hinhAnh.setText("");
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/"+sv.getHinhAnh()));
        Image img = icon.getImage();
        img.getScaledInstance( jLabel1_hinhAnh.getWidth(),jLabel1_hinhAnh.getHeight(), 0);
         jLabel1_hinhAnh.setIcon(icon);
        }
    }
    private void jComboBox1quequanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1quequanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1quequanActionPerformed

    private void jButton1_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_firstActionPerformed
        // TODO add your handling code here:
        index = 0;
        jTable1.setRowSelectionInterval(index, index);
        fillDateSinhVien(index);

    }//GEN-LAST:event_jButton1_firstActionPerformed

    private void jButton1_downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_downActionPerformed
        // TODO add your handling code here:
        if (index == 0) {
        } else {
            index--;
            jTable1.setRowSelectionInterval(index, index);
            fillDateSinhVien(index);
        }
    }//GEN-LAST:event_jButton1_downActionPerformed

    private void jButton1_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_upActionPerformed
        // TODO add your handling code here:
        if (index == dsSinhVien.size() - 1) {
        } else {
            index++;
            jTable1.setRowSelectionInterval(index, index);
            fillDateSinhVien(index);
        }
    }//GEN-LAST:event_jButton1_upActionPerformed

    private void jButton1_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_lastActionPerformed
        // TODO add your handling code here:
        index = dsSinhVien.size() - 1;
        jTable1.setRowSelectionInterval(index, index);
        fillDateSinhVien(index);
    }//GEN-LAST:event_jButton1_lastActionPerformed

    private void jButton1_them1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_them1ActionPerformed

        if (CheckValidateForm()) {
            if (chechMSVTonTai(jTextField2_msv.getText())) {
                JOptionPane.showMessageDialog(this, "Mã Sinh Viên không được trùng");
            } else {
                try {
                    getAllSinhVien();
                    fillDataTable();
                    reset();

                    // TODO add your handling code here:
                } catch (ParseException ex) {
                    Logger.getLogger(QuanLiSV.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin sinh viên");
        }

    }//GEN-LAST:event_jButton1_them1ActionPerformed

    public boolean chechMSVTonTai(String msv) {
        for (SinhVien sv : dsSinhVien) {
            if (sv.getMaSV().equalsIgnoreCase(msv)) {
                return true;
            }
        }
        return false;
    }

    public boolean CheckValidateForm() {
        if (jTextField2_msv.getText().isEmpty()
                || jTextField3thoten.getText().isEmpty()
                || jComboBox1quequan.getSelectedIndex() == -1
                || jTextField5ngaySinh.getText().isEmpty()
                || buttonGroup1.getButtonCount() == 0
                || jTextField9DTB.getText().isEmpty()) {
            return false;
        } else {
            try {
                float tb = Float.parseFloat(jTextField9DTB.getText());
                if (tb < 0 && tb > 10) //JOptionPane.showMessageDialog(this, "Nhập điểm TB chưa đúng");         
                {
                    return false;
                }
            } catch (Exception e) {
                return false;
            }
        }
        return true;
    }
    private void jButton1_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_suaActionPerformed
        // TODO add your handling code here:

        int viTriSua = -1;
        viTriSua = jTable1.getSelectedRow();
        if (CheckValidateForm()) {
            if (viTriSua < 0) {
                JOptionPane.showMessageDialog(this, "Vui long chọn sinh viên cần sửa");
            } else {
                SinhVien sv = new SinhVien();
                sv.setMaSV(jTextField2_msv.getText());
                sv.setHoVaTen(jTextField3thoten.getText());
                int quequan = jComboBox1quequan.getSelectedIndex() - 1;
                Tinh t = Tinh.getbyID(quequan);
                sv.setQueQuan(t);
                try {
                    sv.setNgaySinh(format.parse(jTextField5ngaySinh.getText()));
                } catch (ParseException ex) {
                    Logger.getLogger(QuanLiSV.class.getName()).log(Level.SEVERE, null, ex);
                }
                boolean gt = true;
                gt = jRadioButton1Nam.isSelected();
                sv.setGioiTinh(gt);
                sv.setDiemTB(Float.parseFloat(jTextField9DTB.getText()));
                sv.setHinhAnh(strhinhAnh);
                dsSinhVien.set(viTriSua, sv);
                fillDataTable();
                JOptionPane.showMessageDialog(this, "Đã Cập Nhật");

            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin sinh viên");
        }
    }//GEN-LAST:event_jButton1_suaActionPerformed
    public void saveFile(String duongdan) {
        try {
            
            FileOutputStream fos = new FileOutputStream(duongdan);
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            for (SinhVien sv : dsSinhVien) {
                oos.writeObject(sv);
            }            
            oos.close();
            fos.close();           
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error");
            
        }

    }

    public void openFile(File file) {
        ArrayList<SinhVien> ds = new ArrayList<>();
        try {         
            FileInputStream fis = new FileInputStream(file);
            ObjectInputStream ois = new ObjectInputStream(fis);
            Object doc = ois.readObject();
            ds =  (ArrayList<SinhVien>) doc;
            ois.close();
            fis.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            
        }
        setDsSinhVien(ds);
    }
   public void thuchienSaveFile() throws ParseException {
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File f = fc.getSelectedFile();
             saveFile(f.getAbsolutePath());
                JOptionPane.showMessageDialog(this, "Save thanh cong");
            
        }
    }
    private void jButton1_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_luuActionPerformed
       try {
           thuchienSaveFile();
        } catch (ParseException ex) {
            Logger.getLogger(QuanLiSV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1_luuActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        index = jTable1.getSelectedRow();
        fillDateSinhVien(index);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1_huy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_huy1ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton1_huy1ActionPerformed

    private void jButton1_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_xoaActionPerformed
        // TODO add your handling code here:
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên cần xóa");
        } else {
            index = jTable1.getSelectedRow();
        }
        dsSinhVien.remove(index);
        fillDataTable();
    }//GEN-LAST:event_jButton1_xoaActionPerformed

    public void findSinhVien() {
        int vitriTim = -1;
        for (int i = 0; i < dsSinhVien.size(); i++) {
            SinhVien sv = dsSinhVien.get(i);
            if (sv.getMaSV().equalsIgnoreCase(jTextField1_tim.getText())) {
                vitriTim = i;
                break;
            }
        }
        if (vitriTim < 0) {
            JOptionPane.showMessageDialog(this, "Không Tồn Tại");
        } else {
            reset();
            jTable1.setRowSelectionInterval(vitriTim, vitriTim);
            fillDateSinhVien(vitriTim);
        }
    }
    private void jButton1_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_timActionPerformed
        // TODO add your handling code here:
        if (!jTextField1_tim.getText().isEmpty()) {

            findSinhVien();

        } else {
            JOptionPane.showMessageDialog(this, "Vui long nhập Mã Sinh Viên cần tìm");
        }

    }//GEN-LAST:event_jButton1_timActionPerformed
    public void thucHienTaiLaiDuLieu() {
        while (true) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int soLuongDong = model.getRowCount();
            if (soLuongDong == 0) {
                break;
            } else {
                try {
                    model.removeRow(0);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
        for (SinhVien sv : getDsSinhVien()) {
            dsSinhVien.add(sv);
            fillDataTable();
        }
    }
    public void thuchienopen() {
        JFileChooser jc = new JFileChooser();
        int res = jc.showOpenDialog(this);
        if (res == JFileChooser.APPROVE_OPTION) {
            File f = jc.getSelectedFile();
            openFile(f);
            thucHienTaiLaiDuLieu();
            JOptionPane.showMessageDialog(this, "Mở Thành công");
        }
    }
    private void jButton1_openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_openFileActionPerformed
        try {
            thuchienopen();         
        } catch (Exception e) {
            e.printStackTrace();
        }       
    }//GEN-LAST:event_jButton1_openFileActionPerformed

    public ImageIcon ResizeImage(String anh){
        ImageIcon icon = new ImageIcon(anh);
        Image jmg = icon.getImage();
        Image newJmg = jmg.getScaledInstance(jLabel1_hinhAnh.getWidth(), jLabel1_hinhAnh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newJmg);
        return image;
    }
    private void jLabel1_hinhAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_hinhAnhMouseClicked
        // TODO add your handling code here:
        try {
            JFileChooser jc = new JFileChooser("D:\\ProJect\\src\\Images");
            jc.setDialogTitle("Mở file");
            jc.showOpenDialog(null);
            File file = jc.getSelectedFile();
            strhinhAnh = file.getAbsolutePath();
            jLabel1_hinhAnh.setText("");
            if (strhinhAnh != null) {
                jLabel1_hinhAnh.setIcon(ResizeImage(String.valueOf(strhinhAnh)));
                System.out.println(strhinhAnh);
            }
            
        } catch (Exception e) {
           
            System.out.println(strhinhAnh);
        }

    }//GEN-LAST:event_jLabel1_hinhAnhMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1_down;
    private javax.swing.JButton jButton1_first;
    private javax.swing.JButton jButton1_huy1;
    private javax.swing.JButton jButton1_last;
    private javax.swing.JButton jButton1_luu;
    private javax.swing.JButton jButton1_openFile;
    private javax.swing.JButton jButton1_sua;
    private javax.swing.JButton jButton1_them1;
    private javax.swing.JButton jButton1_tim;
    private javax.swing.JButton jButton1_tim2;
    private javax.swing.JButton jButton1_up;
    private javax.swing.JButton jButton1_xoa;
    private javax.swing.JComboBox<String> jComboBox1quequan;
    private javax.swing.JLabel jLabel1_hinhAnh;
    private javax.swing.JLabel jLabel1_maSV;
    private javax.swing.JLabel jLabel2_timMSV;
    private javax.swing.JLabel jLabel3_ngaySinh;
    private javax.swing.JLabel jLabel4_hvaTen;
    private javax.swing.JLabel jLabel5_gioiTInh;
    private javax.swing.JLabel jLabel6_diemTb;
    private javax.swing.JLabel jLabel7_queQuan;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1Nam;
    private javax.swing.JRadioButton jRadioButton2Nu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1_tim;
    private javax.swing.JTextField jTextField2_msv;
    private javax.swing.JTextField jTextField3thoten;
    private javax.swing.JTextField jTextField5ngaySinh;
    private javax.swing.JTextField jTextField9DTB;
    // End of variables declaration//GEN-END:variables
}
