/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.UserDAO;

/**
 *
 * @author Tran Quoc Thai - CE181618
 */
public class LoginDialog extends javax.swing.JDialog {

    /**
     * Creates new form LoginDialog
     */
    public LoginDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel_DNHT = new javax.swing.JLabel();
        jLabel_Logo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_DangNhap = new javax.swing.JLabel();
        jLabel_Pass = new javax.swing.JLabel();
        jTextField_DangNhap = new javax.swing.JTextField();
        jButton_DangNhap = new javax.swing.JButton();
        jButton_Huy = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Đăng Nhập");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_DNHT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_DNHT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_DNHT.setText("Đăng Nhập Hệ Thống");

        jLabel_Logo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/security.png"))); // NOI18N
        jLabel_Logo.setText("jLabel2");
        jLabel_Logo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_DangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_DangNhap.setText("Tên Đăng Nhập");

        jLabel_Pass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Pass.setText("Mật Khẩu");

        jTextField_DangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton_DangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_DangNhap.setText("Đăng Nhập");
        jButton_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DangNhapActionPerformed(evt);
            }
        });

        jButton_Huy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Huy.setText("Hủy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_DangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_DangNhap)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_DangNhap)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Huy)
                        .addGap(0, 76, Short.MAX_VALUE))
                    .addComponent(jPasswordField)))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel_DNHT)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_DNHT, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addComponent(jLabel_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_DangNhap)
                            .addComponent(jButton_Huy)))
                    .addComponent(jLabel_Logo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean chechValidateForm(){
        if(jTextField_DangNhap.getText().isEmpty() || jPasswordField.getText().isEmpty()){
            return false;
        }
        return true;
    }
    private void jButton_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DangNhapActionPerformed
       if(chechValidateForm()){
           String username = jTextField_DangNhap.getText();
           String pass = new String(jPasswordField.getPassword());
           UserDAO dao = new UserDAO();
           if(dao.checkLogin(username, pass)){
               FrMainForm main = new FrMainForm();
               main.setVisible(true);
               this.dispose();
           }else {
               JOptionPane.showMessageDialog(this, "Tên Đằng Nhập Hoặc Mật Khẩu Không Đúng!");
           }
       }else {
           JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Tên Đăng Nhập Hoặc Mật Khẩu!");
       }
    }//GEN-LAST:event_jButton_DangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginDialog dialog = new LoginDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_DangNhap;
    private javax.swing.JButton jButton_Huy;
    private javax.swing.JLabel jLabel_DNHT;
    private javax.swing.JLabel jLabel_DangNhap;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLabel jLabel_Pass;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField_DangNhap;
    // End of variables declaration//GEN-END:variables
}
