/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Diem;
import model.DiemDAO;
import model.SinhVien;
import model.SinhVienDAO;

/**
 *
 * @author Tran Quoc Thai - CE181618
 */
public class QuanLiDiemDialog extends javax.swing.JDialog {

    /**
     * Creates new form QuanLiDiemDialog
     */
    public QuanLiDiemDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Quản Lí Điểm Sinh Viên");
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_timMSV = new javax.swing.JLabel();
        jTextField_timMSV = new javax.swing.JTextField();
        jButton_tim = new javax.swing.JButton();
        jLabel_MSV = new javax.swing.JLabel();
        jLabel_HvTen = new javax.swing.JLabel();
        jLabel_Toan = new javax.swing.JLabel();
        jLabel_Li = new javax.swing.JLabel();
        jLabel_Hoa = new javax.swing.JLabel();
        jLabel_TBC = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel_DiemTBC = new javax.swing.JLabel();
        jButton_themD = new javax.swing.JButton();
        jButton_luuD = new javax.swing.JButton();
        jButton_suaD = new javax.swing.JButton();
        jButton_xoaD = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_diem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_timMSV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_timMSV.setText("Mã Sinh Viên :");

        jTextField_timMSV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton_tim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_tim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search.png"))); // NOI18N
        jButton_tim.setText("Tìm");
        jButton_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_timActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel_timMSV, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_timMSV, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton_tim)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_timMSV, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_timMSV, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel_MSV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_MSV.setText("Mã Sinh Viên :");

        jLabel_HvTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_HvTen.setText("Họ Và Tên :");

        jLabel_Toan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Toan.setText("Môn Toán :");

        jLabel_Li.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Li.setText("Môn Lí :");

        jLabel_Hoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Hoa.setText("Môn Hóa :");

        jLabel_TBC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_TBC.setText("Điểm TBC :");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel_DiemTBC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_DiemTBC.setText("0.0");

        jButton_themD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_themD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Create.png"))); // NOI18N
        jButton_themD.setText("Thên");
        jButton_themD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_themDActionPerformed(evt);
            }
        });

        jButton_luuD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_luuD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save.png"))); // NOI18N
        jButton_luuD.setText("Lưu");
        jButton_luuD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_luuDActionPerformed(evt);
            }
        });

        jButton_suaD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_suaD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Notes.png"))); // NOI18N
        jButton_suaD.setText("Sửa");
        jButton_suaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_suaDActionPerformed(evt);
            }
        });

        jButton_xoaD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_xoaD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete.png"))); // NOI18N
        jButton_xoaD.setText("Xóa");
        jButton_xoaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xoaDActionPerformed(evt);
            }
        });

        jTable_diem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SV", "Họ Và Tên", "Toán", "Lí", "Hóa", "TBC", "Xếp Loại"
            }
        ));
        jTable_diem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_diemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_diem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel_TBC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_Hoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_Li, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_Toan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_HvTen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_MSV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton_luuD, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                            .addComponent(jButton_themD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton_suaD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton_xoaD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel_DiemTBC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_MSV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_themD, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_HvTen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_luuD, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Toan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_suaD, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Li, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_xoaD, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Hoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TBC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_DiemTBC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    SinhVienDAO svDao = new SinhVienDAO();
    DiemDAO dDAO = new DiemDAO();
    
    public void fillDataTable(){
        DefaultTableModel model = (DefaultTableModel) jTable_diem.getModel();
        model.setRowCount(0);
        for (Diem diem : dDAO.getAllDiemSV()) {
            Object[] newData = new Object[7];
            newData[0] = diem.getSv().getMaSV();
            newData[1] = diem.getSv().getTenSV();
            newData[2] = diem.getdToan();
            newData[3] = diem.getdLi();
            newData[4] = diem.getdHoa();
            newData[5] = diem.diemTBC();
            newData[6] = diem.xepLoai();
            model.addRow(newData);
        }
    }
    public boolean ValidateForm(){
        if(jTextField1.getText().isEmpty()
                || jTextField2.getText().isEmpty()
                || jTextField3.getText().isEmpty()
                || jTextField4.getText().isEmpty()
                || jTextField5.getText().isEmpty()){
            return false;
        }else{
            try {
                double toan = Double.parseDouble(jTextField3.getText());
                double li = Double.parseDouble(jTextField4.getText());
                double hoa = Double.parseDouble(jTextField5.getText());
                if((toan <0 || toan >10) && (li<0 || li>10) && (hoa<0 || hoa >10)){
                    return false;
                }
            } catch (Exception e) {
                return false;
            }
        }
        return true;              
    }
    public Diem getModel(){
        Diem diem = new Diem();
        diem.setId(0);
        SinhVien sv = new SinhVien(jTextField1.getText(), jTextField2.getText());
        diem.setSv(sv);
        diem.setdToan(Double.parseDouble(jTextField3.getText()));
        diem.setdLi(Double.parseDouble(jTextField4.getText()));
        diem.setdHoa(Double.parseDouble(jTextField5.getText()));
        diem.setTbc(Double.parseDouble(jLabel_DiemTBC.getText()));
        
        return diem;
       
    }
    public void setModel(Diem d){
        jTextField1.setText(d.getSv().getMaSV());
        jTextField2.setText(d.getSv().getTenSV());
        jTextField3.setText(String.valueOf(d.getdToan()));
        jTextField4.setText(String.valueOf(d.getdLi()));
        jTextField5.setText(String.valueOf(d.getdHoa()));
        jLabel_DiemTBC.setText(String.valueOf(d.diemTBC()));
    }
    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton_themDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_themDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_themDActionPerformed

    private void jButton_luuDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_luuDActionPerformed
        // TODO add your handling code here:
        if(ValidateForm()){
            Diem d = getModel();
            if(dDAO.plus(d)>0){
                fillDataTable();
            }
        }else {
            JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra thông tin!");
        }
    }//GEN-LAST:event_jButton_luuDActionPerformed

    private void jButton_suaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_suaDActionPerformed
        // TODO add your handling code here:
        if(ValidateForm()){
            Diem diem = getModel();
            if(dDAO.updateDiemSV(diem)>0){
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                fillDataTable();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin");
        }
    }//GEN-LAST:event_jButton_suaDActionPerformed

    private void jButton_xoaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xoaDActionPerformed
        // TODO add your handling code here:
        if(ValidateForm()){
            if(dDAO.delDiemSV(jTextField1.getText())>0){
                fillDataTable();
            }
        }else {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin");
        }
    }//GEN-LAST:event_jButton_xoaDActionPerformed

    private void jButton_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_timActionPerformed
        // TODO add your handling code here:
        if(jTextField_timMSV.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã Sinh viên cần tìm");
        }else {
            SinhVien sv = svDao.getSinhVienByID(jTextField_timMSV.getText());
            if(sv!=null){
                Diem d = dDAO.getDiemByMaSV(sv.getMaSV());
                if(d!= null){
                    setModel(d);
                }
                else{
                jTextField1.setText(sv.getMaSV());
                jTextField2.setText(sv.getTenSV());
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jLabel_DiemTBC.setText("0.0");
                }
            }                                                                                                           
        }
    }//GEN-LAST:event_jButton_timActionPerformed
    
    private void jTable_diemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_diemMouseClicked
        // TODO add your handling code here:
        int id = jTable_diem.rowAtPoint(evt.getPoint());
        String maSV = jTable_diem.getValueAt(id, 0).toString();
        Diem d = dDAO.getDiemByMaSV(maSV);
        setModel(d);
    }//GEN-LAST:event_jTable_diemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiDiemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiDiemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiDiemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiDiemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLiDiemDialog dialog = new QuanLiDiemDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_luuD;
    private javax.swing.JButton jButton_suaD;
    private javax.swing.JButton jButton_themD;
    private javax.swing.JButton jButton_tim;
    private javax.swing.JButton jButton_xoaD;
    private javax.swing.JLabel jLabel_DiemTBC;
    private javax.swing.JLabel jLabel_Hoa;
    private javax.swing.JLabel jLabel_HvTen;
    private javax.swing.JLabel jLabel_Li;
    private javax.swing.JLabel jLabel_MSV;
    private javax.swing.JLabel jLabel_TBC;
    private javax.swing.JLabel jLabel_Toan;
    private javax.swing.JLabel jLabel_timMSV;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_diem;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField_timMSV;
    // End of variables declaration//GEN-END:variables
}
